# -*- coding: utf-8 -*-
"""projektmunka.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jzCm9qXV-RRye54edau6hIjT2-AtlCJg
"""

!pip install transformers

from transformers import pipeline
from bs4 import BeautifulSoup
import requests
import re

MODEL_ID = "facebook/bart-large-cnn" #@param {type: "string"}

#Kipróbált modellek:
# "Falconsai/text_summarization" -> Magyar szöveg kuka
# "SZTAKI-HLT/mT5-base-HunSum-1" -> Nem jól dolgozza fel a szöveget, értelmezhetetlen
# NYTK/summarization-hi-mt5-base-hungarian -> Tökéletes volt magyar szövegre, angolra nem fine tuningolt
# slauw87/bart_summarisation -> Fő problémánk vele az volt, hogy inkonzisztens valamely szövegekre tényleg emberinek tűnő választ adott mondjuk azt 10/4 esetben de a maradékban abszolút hülyeséget
# facebook/bart-large-cnn -> Legjobb opciónk volt mert a magyar szöveget is 10/8 esetben jól fordította de az angolt abszolút perfektül

summarizer = pipeline("summarization", model=MODEL_ID)

URL = 'https://magyarugyved.blog.hu/' #@param {type:"string"}

r = requests.get(URL)

soup = BeautifulSoup(r.text, 'html.parser')
results = soup.find_all(['h1', 'p'])
text = [result.text for result in results]
ARTICLE = ' '.join(text)

ARTICLE

max_chunk = 250 #@param {type:"int"};

ARTICLE = ARTICLE.replace('.', '.<eos>')
ARTICLE = ARTICLE.replace('?', '?<eos>')
ARTICLE = ARTICLE.replace('!', '!<eos>')

sentences = ARTICLE.split('<eos>')
current_chunk = 0
chunks = []
for sentence in sentences:
    if len(chunks) == current_chunk + 1:
        if len(chunks[current_chunk]) + len(sentence.split(' ')) <= max_chunk:
            chunks[current_chunk].extend(sentence.split(' '))
        else:
            current_chunk += 1
            chunks.append(sentence.split(' '))
    else:
        print(current_chunk)
        chunks.append(sentence.split(' '))

for chunk_id in range(len(chunks)):
    chunks[chunk_id] = ' '.join(chunks[chunk_id])

len(chunks)

MAX_LENGTH = 120 #@param {type:"int"};
MIN_LENGTH = 30 #@param {type:"int"};

res = summarizer(chunks, max_length=MAX_LENGTH, min_length=MIN_LENGTH, do_sample=False)

res[0]

' '.join([summ['summary_text'] for summ in res])

text = ' '.join([summ['summary_text'] for summ in res])

with open('blogsummary.txt', 'w') as f:
    f.write(text)